title: Ansh Arora
email: ansharora@umass.edu
description: >-
  Personal academic website showcasing bio, CV, publications, and contact details.
baseurl: ""
url: "https://ansharora7.github.io"

remote_theme: "mmistakes/minimal-mistakes"

header_sticky: true
custom_css:
  - "/assets/css/custom.css"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

gems:
  - jekyll-include-cache

markdown: kramdown

author:
  name: "Ansh Arora"
  avatar: "/assets/images/profile.jpg"
  bio: "Graduate student in CS at UMass Amherst, focusing on AI security, deep learning, and natural language processing."
  location: "Amherst, Massachusetts, U.S.A"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ansharora@umass.edu"
    - label: "CV"
      icon: "fas fa-file"
      url: "/assets/files/resume.pdf"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=P-CP_R4AAAAJ&hl=en&oi=ao"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ansharora7"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/anshkarora"

navigation:
  - title: "CV"
    url: "/assets/files/resume.pdf"
    external: true
  - title: "Publications"
    url: "/publications/"

header:
  nav: true

# Removed header_pages to avoid conflicts

minimal_mistakes_skin: "default"

footer:
  custom: custom-footer
